
name: Lab1
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x ./flaskapp/st.sh
      - run: pip3 install flask
      - run: pip3 install gunicorn
      - run: pip3 install requests
      - name: Change directory
        shell: bash
        run: ./st.sh
        working-directory: ./flaskapp
