
name: Lab1
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: -pip3 install flask
      - name: Run a script
      - run: python3 ./flaskapp/some_app.py
